{
 "title": "K8s Infara Status Board Ver.2",
 "description": "This dashboard is one of major topic for Kubernetes Book \nand best optimized for virtual machine environment provided with \nhttps://github.com/sysnet4admin/_Book_k8sInfra\n\nNotice: It may be running on the other environment but cannot be guaranteed.",
 "tags": [
  "infra",
  "squars-apps",
  "k8s"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "query": {
     "query": "label_values(kube_node_created, node)"
    }
   },
   {
    "name": "apps",
    "query": {
     "query": "label_values(kube_pod_labels{label_squars_io_app!=\"\"}, label_squars_io_app)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "query_result(node_uname_info{nodename=\"$node\"})"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_labels{label_squars_io_app=\"$apps\"}, namespace)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(kube_pod_labels{namespace=\"$namespace\", label_squars_io_app=\"$apps\"}, pod)"
    }
   },
   {
    "name": "cpu_core",
    "query": {
     "query": "query_result(count(node_cpu_seconds_total{mode=\"idle\"}) by (instance))"
    }
   },
   { "name": "duration", "query": "2m,5m,10m,30m,1h" },
   {
    "name": "pod_name",
    "query": {
     "query": "label_values(kube_pod_labels{namespace=\"$namespace\",label_squars_io_app=\"$apps\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "전체 노드",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "노드별 CPU 점유율",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(\n  sum by (instance, nodename) (irate(node_cpu_seconds_total{mode!~\"guest.*|idle|iowait\"}[$duration])) \n  + \n  on(instance) group_left(nodename) (max(node_uname_info) by (instance, nodename))\n) / $cpu_core - 1/$cpu_core\n",
     "legendFormat": "{{nodename}} "
    }
   ]
  },
  {
   "title": "노드별 메모리 사용량",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "(\n  node_memory_MemTotal_bytes  \n  + \n  on(instance) group_left(nodename) max(node_uname_info) by (instance, nodename)\n) \n-\n( \n  node_memory_MemAvailable_bytes  \n  + \n  on(instance) group_left(nodename) max(node_uname_info) by (instance, nodename)\n)\n",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "노드 리소스 대시보드",
   "type": "table-old",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "node_uname_info{job=~\"node-exporter\"} - 0",
     "legendFormat": "Hostname"
    },
    {
     "expr": "sum(time() - node-exporter{job=~\"node-exporter\"})by(instance)",
     "legendFormat": "Uptime"
    },
    {
     "expr": "node_memory_MemTotal_bytes{job=~\"node-exporter\"} - 0",
     "legendFormat": "Memory"
    },
    {
     "expr": "count(node_cpu_seconds_total{job=~\"node-exporter\",mode='system'}) by (instance)",
     "legendFormat": "Cpu Core"
    },
    {
     "expr": "node_load5{job=~\"node-exporter\"}",
     "legendFormat": "5m load"
    },
    {
     "expr": "(1 - avg(rate(node_cpu_seconds_total{job=~\"node-exporter\",mode=\"idle\"}[$duration])) by (instance)) * 100",
     "legendFormat": "CPU 사용량"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{job=~\"node-exporter\"} / (node_memory_MemTotal_bytes{job=~\"node-exporter\"})))* 100",
     "legendFormat": "Memory 사용량"
    },
    {
     "expr": "max((node_filesystem_size_bytes{job=~\"node-exporter\",fstype=~\"ext.?|xfs\"}-node_filesystem_free_bytes{job=~\"node-exporter\",fstype=~\"ext.?|xfs\"}) *100/(node_filesystem_avail_bytes {job=~\"node-exporter\",fstype=~\"ext.?|xfs\"}+(node_filesystem_size_bytes{job=~\"node-exporter\",fstype=~\"ext.?|xfs\"}-node_filesystem_free_bytes{job=~\"node-exporter\",fstype=~\"ext.?|xfs\"})))by(instance)",
     "legendFormat": "Partiion 사용량"
    },
    {
     "expr": "sum(rate(node_disk_read_bytes_total{job=~\"node-exporter\"}[$duration])) by (instance)",
     "legendFormat": "디스크 읽기"
    },
    {
     "expr": "max(rate(node_disk_written_bytes_total{job=~\"node-exporter\"}[$duration])) by (instance)",
     "legendFormat": "디스크 쓰기"
    },
    {
     "expr": "node_netstat_Tcp_CurrEstab{job=~\"node-exporter\"} - 0",
     "legendFormat": "Tcp Established"
    },
    {
     "expr": "node_sockstat_TCP_tw{job=~\"node-exporter\"} - 0",
     "legendFormat": "TIME_WAIT"
    },
    {
     "expr": "max(rate(node_network_receive_bytes_total{job=~\"node-exporter\"}[2m])*8) by (instance)",
     "legendFormat": "Download"
    },
    {
     "expr": "max(rate(node_network_transmit_bytes_total{job=~\"node-exporter\"}[2m])*8) by (instance)",
     "legendFormat": "Upload"
    }
   ]
  },
  {
   "title": "노드 $node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "CPU 사용률(%)",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 3, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum by (instance) (irate(node_cpu_seconds_total{mode!~\"guest.*|idle|iowait\", instance=\"$instance\",pod!=\"\"}[$duration])) / $cpu_core"
      }
     ]
    },
    {
     "title": "메모리 사용률(%)",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 3, "x": 3, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "(node_memory_MemTotal_bytes{instance=\"$instance\"}-node_memory_MemAvailable_bytes{instance=\"$instance\"})/node_memory_MemTotal_bytes{instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "디스크 사용률(%)",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 3, "x": 6, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(node_filesystem_size_bytes{instance=\"$instance\"} - node_filesystem_avail_bytes{instance=\"$instance\"}) by (instance) / sum(node_filesystem_size_bytes{instance=\"$instance\"}) by (instance)"
      }
     ]
    },
    {
     "title": "Uptime",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 9, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": " (\n ((time() - node_boot_time_seconds + on(instance) group_left(nodename) \nnode_uname_info{nodename=\"$node\"})) \nand \nON() kube_node_status_condition{status=\"true\",condition=\"Ready\",node=\"$node\"} == 1 \n) "
      }
     ]
    },
    {
     "title": "Node Conditions",
     "type": "grafana-polystat-panel",
     "gridPos": { "h": 3, "w": 3, "x": 13, "y": 2 },
     "targets": [
      {
       "expr": "(kube_node_status_condition{status=\"true\",condition=~\"MemoryPressure|PIDPressure|DiskPressure\",service=\"k8s-prometheus-stack-kube-state-metrics\",node=\"$node\"})",
       "legendFormat": "{{condition}}"
      }
     ]
    },
    {
     "title": "Pod count by NameSpace",
     "type": "piechart",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count by (namespace)(kube_pod_info{node=\"$node\"})",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "CPU 코어",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 9, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      { "expr": "$cpu_core" }
     ]
    },
    {
     "title": "메모리",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 11, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(node_memory_MemTotal_bytes{instance=~\"$instance\"}) - 0"
      }
     ]
    },
    {
     "title": "pod count",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 13, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(kube_pod_info{node=\"$node\"})",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Pod CPU 점유율",
     "type": "graph",
     "gridPos": { "h": 16, "w": 12, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum by (pod,namespace) (rate(container_cpu_usage_seconds_total{node=\"$node\",pod!=\"\"}[5m])) * 100 / $cpu_core",
       "legendFormat": "{{pod}} / {{namespace}}"
      }
     ]
    },
    {
     "title": "Pod Memory 사용량",
     "type": "graph",
     "gridPos": { "h": 16, "w": 12, "x": 12, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by (pod,namespace)(container_memory_working_set_bytes{node=\"$node\",pod!=\"\"})",
       "legendFormat": "{{pod}} / {{namespace}}"
      }
     ]
    },
    {
     "title": "초당 네트워크 트래픽",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum (rate(node_network_receive_bytes_total{instance=\"$instance\"}[$duration]))",
       "legendFormat": "$node (in)"
      },
      {
       "expr": "sum (rate(node_network_transmit_bytes_total{instance=\"$instance\"}[$duration]))",
       "legendFormat": "$node (out)"
      }
     ]
    },
    {
     "title": "Disk I/O",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "yaxes": [
      { "format": "decbytes", "label": "읽기 | 쓰기" }
     ],
     "targets": [
      {
       "expr": "sum (rate(node_disk_read_bytes_total{instance=\"$instance\"}[$duration])) by (pod)",
       "legendFormat": "Disk IO(Read)"
      },
      {
       "expr": "max(rate(node_disk_written_bytes_total{instance=\"$instance\"}[$duration])) by (pod)",
       "legendFormat": "Disk IO(Write)"
      }
     ]
    }
   ]
  },
  {
   "title": "$pod / $namespace",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {}
   ]
  },
  {
   "title": "$apps pod 대시보드",
   "type": "table-old",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "node_uname_info{job=~\"node-exporter\"} - 0",
     "legendFormat": "Hostname"
    },
    {
     "expr": "sum(time() - node-exporter{job=~\"node-exporter\"})by(instance)",
     "legendFormat": "Uptime"
    },
    {
     "expr": "node_memory_MemTotal_bytes{job=~\"node-exporter\"} - 0",
     "legendFormat": "Memory"
    },
    {
     "expr": "count(node_cpu_seconds_total{job=~\"node-exporter\",mode='system'}) by (instance)",
     "legendFormat": "Cpu Core"
    },
    {
     "expr": "node_load5{job=~\"node-exporter\"}",
     "legendFormat": "5m load"
    },
    {
     "expr": "(1 - avg(rate(node_cpu_seconds_total{job=~\"node-exporter\",mode=\"idle\"}[$duration])) by (instance)) * 100",
     "legendFormat": "CPU 사용량"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{job=~\"node-exporter\"} / (node_memory_MemTotal_bytes{job=~\"node-exporter\"})))* 100",
     "legendFormat": "Memory 사용량"
    },
    {
     "expr": "max((node_filesystem_size_bytes{job=~\"node-exporter\",fstype=~\"ext.?|xfs\"}-node_filesystem_free_bytes{job=~\"node-exporter\",fstype=~\"ext.?|xfs\"}) *100/(node_filesystem_avail_bytes {job=~\"node-exporter\",fstype=~\"ext.?|xfs\"}+(node_filesystem_size_bytes{job=~\"node-exporter\",fstype=~\"ext.?|xfs\"}-node_filesystem_free_bytes{job=~\"node-exporter\",fstype=~\"ext.?|xfs\"})))by(instance)",
     "legendFormat": "Partiion 사용량"
    },
    {
     "expr": "sum(rate(node_disk_read_bytes_total{job=~\"node-exporter\"}[$duration])) by (instance)",
     "legendFormat": "디스크 읽기"
    },
    {
     "expr": "max(rate(node_disk_written_bytes_total{job=~\"node-exporter\"}[$duration])) by (instance)",
     "legendFormat": "디스크 쓰기"
    },
    {
     "expr": "node_netstat_Tcp_CurrEstab{job=~\"node-exporter\"} - 0",
     "legendFormat": "Tcp Established"
    },
    {
     "expr": "node_sockstat_TCP_tw{job=~\"node-exporter\"} - 0",
     "legendFormat": "TIME_WAIT"
    },
    {
     "expr": "max(rate(node_network_receive_bytes_total{job=~\"node-exporter\"}[2m])*8) by (instance)",
     "legendFormat": "Download"
    },
    {
     "expr": "max(rate(node_network_transmit_bytes_total{job=~\"node-exporter\"}[2m])*8) by (instance)",
     "legendFormat": "Upload"
    }
   ]
  },
  {
   "title": "$apps Pod 생성시간",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "time() - kube_pod_start_time{namespace=\"$namespace\",pod=~\"$pod_name\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Pod 가동 상태",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 7, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_reason{pod=\"$pod\", reason!~\"ContainerCreating\"})"
    }
   ]
  },
  {
   "title": "10분 이내 재시작",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(round(increase(kube_pod_container_status_restarts_total{pod=\"$pod\"}[10m])))"
    }
   ]
  },
  {
   "title": "리소스 사용량",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 11, "x": 13, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{pod=\"$pod\"})",
     "legendFormat": "Memory(bytes)"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=\"$pod\"}[$duration])) / $cpu_core",
     "legendFormat": "CPU(%)"
    },
    {
     "expr": "sum(container_fs_usage_bytes{pod=\"$pod\"})",
     "legendFormat": "File system usage"
    }
   ]
  },
  {
   "title": "메모리 사용량",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{pod=\"$pod\"})",
     "legendFormat": "Memory Useage"
    }
   ]
  },
  {
   "title": "CPU 사용률(%)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 13, "x": 11, "y": 26 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{pod=\"$pod\"}[5m])) * 100 / $cpu_core",
     "legendFormat": "CPU Useage"
    },
    {}
   ]
  },
  {
   "title": "초당 네트워크 트래픽",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{pod=\"$pod\"}[$duration]))",
     "legendFormat": "in"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{pod=\"$pod\"}[$duration]))",
     "legendFormat": "out"
    }
   ]
  }
 ]
}