{
 "title": "SQUARS POD Status Board Ver.0.1.1",
 "description": "This dashboard is one of major topic for Kubernetes Book \nand best optimized for virtual machine environment provided with \nhttps://github.com/sysnet4admin/_Book_k8sInfra\n\nNotice: It may be running on the other environment but cannot be guaranteed.",
 "tags": [
  "infra",
  "squars-apps",
  "k8s"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "node",
    "query": {
     "query": "label_values(kube_node_created, node)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_labels{label_squars_io_app=\"$apps\"}, namespace)"
    }
   },
   {
    "name": "apps",
    "query": {
     "query": "label_values(kube_pod_labels{label_squars_io_app!=\"\"}, label_squars_io_app)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(kube_pod_labels{namespace=\"$namespace\", label_squars_io_app=\"$apps\"}, pod)"
    }
   },
   {
    "name": "cpu_core",
    "query": {
     "query": "query_result(count(node_cpu_seconds_total{mode=\"idle\"}) by (instance))"
    }
   },
   { "name": "duration", "query": "2m,5m,10m,30m,1h" },
   {
    "name": "pod_name",
    "query": {
     "query": "label_values(kube_pod_labels{namespace=\"$namespace\",label_squars_io_app=\"$apps\"}, pod)"
    }
   },
   {
    "name": "level",
    "query": "ERROR,WARN,INFO,DEBUG,TRACE,FATAL"
   },
   { "name": "search", "query": ".*" },
   { "name": "regex", "query": ".*" }
  ]
 },
 "panels": [
  { "title": "$namespace POD status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Stage Pod Status",
   "type": "table",
   "gridPos": { "h": 13, "w": 19, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "count(kube_pod_info{namespace=\"$namespace\"}) by (pod)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\"}[5m])* 1000) by (pod)"
    },
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"$namespace\"}) by (pod)"
    },
    {
     "expr": "kube_pod_status_phase{namespace=\"$namespace\"}==1 "
    },
    {
     "expr": "sum(rate(container_network_receive_bytes_total{namespace=\"$namespace\"}[5m])) by (pod)"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{namespace=\"$namespace\"}[5m])) by (pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=\"$namespace\", resource=\"cpu\",container!=\"istio-proxy\"}) by (pod)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=\"$namespace\", resource=\"memory\",container!=\"istio-proxy\"}) by (pod)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(kube_pod_container_status_restarts_total{namespace=\"$namespace\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$pod / $namespace",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {}
   ]
  },
  {
   "title": "$apps Pod 생성시간",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "time() - kube_pod_start_time{namespace=\"$namespace\",pod=~\"$pod_name\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Pod 가동 상태",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 7, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_reason{pod=\"$pod\", reason!~\"ContainerCreating\"})"
    }
   ]
  },
  {
   "title": "10분 이내 재시작",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 9, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(round(increase(kube_pod_container_status_restarts_total{pod=\"$pod\"}[10m])))"
    }
   ]
  },
  {
   "title": "초당 네트워크 트래픽",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 13, "x": 11, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{pod=\"$pod\"}[$duration]))",
     "legendFormat": "in"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{pod=\"$pod\"}[$duration]))",
     "legendFormat": "out"
    }
   ]
  },
  {
   "title": "메모리 사용량",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{pod=\"$pod\"})",
     "legendFormat": "Memory Useage"
    }
   ]
  },
  {
   "title": "CPU 사용률(m)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 6, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{pod=\"$pod\"}[5m])) * 1000",
     "legendFormat": "CPU Useage"
    }
   ]
  },
  {
   "title": "리소스 사용량",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{pod=\"$pod\"})",
     "legendFormat": "Memory(bytes)"
    },
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{pod=\"$pod\"}[5m])) * 1000",
     "legendFormat": "CPU(m)"
    }
   ]
  },
  {
   "title": "Server Log",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "{namespace=\"$namespace\", pod=\"$pod\", container!=\"istio-proxy\"} |~ `(?i)$search` |~ \"$level\""
    }
   ]
  },
  {
   "title": "Web access Log",
   "type": "logs",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "{namespace=\"$namespace\", pod=\"$pod\", container=\"istio-proxy\"} |~ `(?i)$search` |~ \"$level\""
    }
   ]
  }
 ]
}